In [6]:
import torch
import numpy as np
x = torch.rand(5,3)
print(x)

tensor([[0.9701, 0.7942, 0.8681],
        [0.6948, 0.9907, 0.3665],
        [0.9805, 0.0412, 0.9347],
        [0.9471, 0.4125, 0.0997],
        [0.7457, 0.2814, 0.3419]])


In [7]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [20]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.1973, 0.9984, 0.6697],
        [0.0147, 0.6597, 0.6923]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [21]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
